import gmplot as gm
import webbrowser
import os

apikey = 'AIzaSyCJfnE-UzN0Hc89l89kxl6D8MkVopUYtO4' # (API key here)

gmap = gm.GoogleMapPlotter(6.2106275, -75.5705202, 17, apikey=apikey, map_type="roadmap")

def open_gmap():
    gmap.draw("map.html")
    map_path = os.path.abspath("map.html")
    webbrowser.open(map_path ,new=1)

"""
Highlight the limit of the map (medellin_full.csv)
"""

"""
Takes the path generated by the algorithm to plot on the google map
It is necessary to split and organize the latitudes and longitudes
"""
def mark_route(path, color):
    lats = []
    lons = []
    
    for elem in path:
        elem = elem.split(',')
        lats.append(float(elem[1].strip().strip(')')))
        lons.append(float(elem[0].strip('(')))
    
    gmap.plot(lats, lons, color=color, edge_width = 10.0)
    gmap.marker(lats[0], lons[0], 'green', title="source", label='S')
    gmap.marker(lats[-1], lons[-1], 'yellow', title="destination", label='D')
    open_gmap()



# entrada = input()
# location = gm.GoogleMapPlotter.geocode(f"{entrada}, medellin colombia", apikey=apikey)
# print(location)

