import webbrowser

"""
The function to generate the .html file and open it using the absolute path and webbrowser.open()
"""
def open_gmap(gmap):
    gmap.draw("map.html")
    # map_path = os.path.abspath("map.html")
    webbrowser.open('map.html', new=1)

"""
Takes the path generated by the algorithm to plot on the google map
It is necessary to split and organize the latitudes and longitudes
"""
def mark_route(path, color, gmap):
    lats = []
    lons = []
    
    for elem in path:
        elem = elem.split(',')
        lats.append(float(elem[1].strip().strip(')')))
        lons.append(float(elem[0].strip('(')))
    
    gmap.plot(lats, lons, color=color, edge_width = 10.0)
    gmap.marker(lats[0], lons[0], 'green', title="source", label='S')
    gmap.marker(lats[-1], lons[-1], 'yellow', title="destination", label='D')